library identifier: 'pipeline-library@main', retriever: modernSCM(
    [$class       : 'GitSCMSource',
     remote       : 'https://github.com/jarryDk/pipeline-library.git'
    ])

sayHello 'Dave'

String hello getHello

sayHello ${hello}