pipeline {

    // agent any
    agent  { label 'quarkus' }

    stages {
        stage('Build') {
            steps {
                sh 'cd HelloQuarkus'
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing HelloPipeline ..'
            }
        }
    }
}