pipeline {
    
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building HelloPipeline ..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing HelloPipeline ..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying HelloPipeline ..'
            }
        }
    }
}